OFTM2/apps/fencers_management/urls.py
'''Fencers Management URL Config'''
from django.urls import path
from . import views

app_name = 'fencers_management'

urlpatterns = [
    path('', views.FencersListView.as_view(), name='fencers_list'),
    path('<int:fencer_id>', views.FencersDetailView.as_view(), name='fencer_detail'),
    path('add', views.FencersCreateView.as_view(), name='fencer_create'),
    path('<int:pk>/update', views.FencersUpdateView.as_view(), name='fencer_update'),
    path('<int:pk>/delete', views.FencersDeleteView.as_view(), name='fencer_delete'),
]

OFTM2/urls.py
"""Root URL Config"""
import debug_toolbar
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='portal.html'), name="portal"),
    path('admin/', admin.site.urls),
    path('fencers/', include('OFTM2.apps.fencers_management.urls')),
                  path('tournaments/', include('OFTM2.apps.tournament_management.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('beamer', include('OFTM2.apps.beamerManagement.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

OFTM2/apps/fencers_management/models.py
"""Models for fencers management app"""
from django.db import models
from django.urls import reverse
from OFTM2.apps.fencers_management.validators import validate_fechtpass
from OFTM2.apps.fencers_management.helpers import calculate_age
from partial_date import PartialDateField

# Create your models here.


class Fencer(models.Model):
    """fencer model represents a fencer"""
    GENDER_MALE = 0
    GENDER_FEMALE = 1
    GENDER_CHOICES = [
        (GENDER_MALE, 'Männlich'),
        (GENDER_FEMALE, 'Weiblich')
    ]

    first_name = models.CharField(
        verbose_name='Vorname',
        max_length=60
    )
    last_name = models.CharField(
        verbose_name='Nachname',
        max_length=60
    )
    gender = models.IntegerField(
        verbose_name='Geschlecht',
        choices=GENDER_CHOICES
    )
    fechtpass = models.CharField(
        verbose_name='Fechtpass Nummer',
        blank=True,
        validators=[
            validate_fechtpass,
        ],
        max_length=9,
        unique=True,
    )
    birthday = models.DateField(
        verbose_name='Geburtsdatum'
    )

    def __str__(self):
        """returns the first and the last name"""
        return '{} {}'.format(self.first_name, self.last_name)

    def get_absolute_url(self):
        """returns the absolute url to the object"""
        return reverse('fencers_management:fencer_detail', args=[str(self.id)])

    def get_ageclasses(self):
        """returns the ageclasses for the fencer"""
        out = []
        age = calculate_age(self.birthday)
        for ageclass in AgeClass.objects.all():
            if ageclass.startAge <= age <= ageclass.endAge:
                out.append(ageclass)
        return out

    def get_age(self):
        """returns the age of a fencer"""
        return calculate_age(self.birthday)

    class Meta:
        verbose_name = "Fechter/in"
        verbose_name_plural = "Fechter/innen"


class AgeClass(models.Model):
    """represents a ageclass (see https://de.wikipedia.org/wiki/Fechten#Altersklassen)"""
    name = models.CharField(
        verbose_name="Name",
        max_length=60
    )
    startAge = models.IntegerField(
        verbose_name="Anfangs Alter",
    )
    endAge = models.IntegerField(
        verbose_name="End Alter"
    )

    def __str__(self):
        """returns the name"""
        return self.name

    class Meta:
        verbose_name = "Altersklasse"
        verbose_name_plural = "Altersklassen"

OFTM2/apps/fencers_management/forms.py
"""Forms for fencers_management"""

from django.forms import ModelForm
from OFTM2.apps.fencers_management.models import Fencer


class FencerForm(ModelForm):
    class Meta:
        model = Fencer
        fields = ['first_name', 'last_name', 'gender', 'birthday', 'fechtpass']

    def __init__(self, *args, **kwargs):
        super(FencerForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'mdl-textfield__input'

OFTM2/apps/fencers_management/views.py
"""view for the fencers management app"""
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.views import View
from django_tables2 import RequestConfig
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from OFTM2.apps.fencers_management.models import Fencer
from OFTM2.apps.fencers_management.tables import FencersTable
from OFTM2.apps.fencers_management.forms import FencerForm
from OFTM2.apps.fencers_management.helpers import calculate_age#

class FencersListView(PermissionRequiredMixin, View):
    permission_required = 'Fencers.can_view'
    """show all fencers as a table"""
    def get(self, request):
        """HTTP-GET"""
        table = FencersTable(Fencer.objects.all())
        RequestConfig(request).configure(table)
        return render(request, 'fencers_list.html', {'table': table, 'title': "Liste der Fechter/innen"})


class FencersDetailView(PermissionRequiredMixin, View):
    permission_required = 'Fencers.can_view'
    """show one fencer"""
    def get(self, request, fencer_id):
        """HTTP-GET"""
        fencer = get_object_or_404(Fencer, pk=fencer_id)
        return render(request, 'fencer_detail.html', {'fencer': fencer, 'back': True, 'title': fencer, 'age': calculate_age(fencer.birthday)})


class FencersCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'Fencers.can_create'
    """create a new fencer"""
    form_class = FencerForm
    template_name = 'fencer_form.html'
    model = Fencer


class FencersUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'Fencers.can_modify'
    """update a fencer"""
    form_class = FencerForm
    template_name = 'fencer_form.html'
    model = Fencer


class FencersDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'Fencers.can_delete'
    """delete a fencer"""
    model = Fencer
    template_name = "fencer_delete.html"
    success_url = reverse_lazy('fencers_management:fencers_list')

OFTM2/apps/fencers_management/templates/fencer_create.html
{% extends "base.html" %}

{% block content %}
    <div class="mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
        <form method="post" class="mdl-cell mdl-cell--12-col mdl-grid" novalidate action="{% url 'fencers_management:fencer_create' %}">
            {% csrf_token %}

            {{ form.non_field_errors }}

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.first_name.id_for_label }}">Vorname</label>
                {{ form.first_name }}
                {{ form.first_name.errors }}
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.last_name.id_for_label }}">Nachname</label>
                {{ form.last_name }}
                {{ form.last_name.errors }}
            </div>


            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select mdl-cell mdl-cell--12-col">
                <input type="text" value="" class="mdl-textfield__input" id="{{ form.gender.id_for_label }}" readonly>
                <input type="hidden" value="" name="gender">
                <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                <label for="{{ form.gender.id_for_label }}" class="mdl-textfield__label">Geschlect</label>
                <ul for="{{ form.gender.id_for_label }}" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    {% for choice in form.fields.gender.choices %}
                        {% if fencer and fencer.gender == choice.0 %}
                        <li class="mdl-menu__item" data-val="{{ choice.0 }}" data-selected="true">{{ choice.1 }}</li>
                        {% else %}
                        <li class="mdl-menu__item" data-val="{{ choice.0 }}">{{ choice.1 }}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
                {{ form.gender.errors }}
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.fechtpass.id_for_label }}">Fechtpass NR.</label>
                {{ form.fechtpass }}
                {{ form.fechtpass.errors }}
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.birthday.id_for_label }}">Geburtsdatum</label>
                {{ form.birthday }}
                {{ form.birthday.errors }}
            </div>
            <div class="mdl-cell--12-col mdl-cell mdl-grid mdl-grid--no-spacing">
                <div class="mdl-layout-spacer"></div>
                <div class="mdl-cell mdl-cell--2-col">
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--red" type="reset">
                        Löschen
                    </button>
                </div>
                <div class="mdl-cell mdl-cell--2-col">
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">
                        Absenden
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

OFTM2/apps/fencers_management/templates/fencer_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="mdl-cell mdl-cell--12-col mdl-grid mdl-shadow--2dp mdl-color--white">
        <div class="mdl-layout-spacer"></div>
        <div class="mdl-cell--4-col">
            <form method="post">
                {% csrf_token %}
                <p style="text-align: center">
                    {{ fencer.first_name }} {{ fencer.last_name }} wirklich löschen?<br>
                    <a href="{{ fencer.get_absolute_url }}">
                        <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="button">
                            Abbruch
                        </button>
                    </a>
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--red" type="submit">
                        Bestätigen
                    </button>
                </p>
            </form>
        </div>
        <div class="mdl-layout-spacer"></div>
    </div>
{% endblock %}

OFTM2/apps/fencers_management/templates/fencer_detail.html
{% extends "base.html" %}

{% block content %}
    {% if perms.Fencers.can_modify or perms.Fencers.can_delete %}
    <div class="mdl-color--white mdl-shadow--2dp mdl-cell--12-col mdl-cell mdl-grid">
        <div class="mdl-layout-spacer"></div>
        {% if perms.Fencers.can_delete %}
        <div class="mdl-cell--1-col mdl-cell">
            <a href="{% url 'fencers_management:fencer_delete' fencer.pk %}">
                <button class="mdl-button mdl-js-button mdl-button--mini-fab mdl-button--colored mdl-color--red mdl-color-text--white">
                    <i class="material-icons">delete</i>
                </button>
            </a>
        </div>
        {% endif %}
        {% if perms.Fencers.can_modify %}
        <div class="mdl-cell--1-col mdl-cell">
            <a href="{% url 'fencers_management:fencer_update' fencer.pk %}">
                <button class="mdl-button mdl-js-button mdl-button--mini-fab mdl-button--colored mdl-shadow--2dp">
                    <i class="material-icons">edit</i>
                </button>
            </a>
        </div>
        {% endif %}
    </div>
    {% endif %}
    <div class="mdl-color--white mdl-shadow--2dp mdl-cell--6-col mdl-cell mdl-grid">
        <div class="fencer-image">
            <i class="material-icons fencer-image-placeholder">
                person_outline
            </i>
        </div>
    </div>
    <div class="mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--6-col mdl-grid">
        <div class="mdl-cell mdl-cell--12-col mdl-grid mdl-shadow--2dp">
            <div class="mdl-cell mdl-cell--6-col">Vorname:</div>
            <div class="mdl-cell mdl-cell--4-col">{{ fencer.first_name }}</div>
        </div>
        <div class="mdl-cell mdl-cell--12-col mdl-grid mdl-shadow--2dp">
            <div class="mdl-cell mdl-cell--6-col">Nachname:</div>
            <div class="mdl-cell mdl-cell--4-col">{{ fencer.last_name }}</div>
        </div>
        <div class="mdl-cell mdl-cell--12-col mdl-grid mdl-shadow--2dp">
            <div class="mdl-cell mdl-cell--6-col">Geschlecht:</div>
            <div class="mdl-cell mdl-cell--4-col">{{ fencer.get_gender_display }}</div>
        </div>
        <div class="mdl-cell mdl-cell--12-col mdl-grid mdl-shadow--2dp">
            <div class="mdl-grid mdl-cell--12-col">
                <div class="mdl-cell mdl-cell--6-col">Geburtsdatum:</div>
                <div class="mdl-cell mdl-cell--4-col">{{ fencer.birthday }}({{ age }})</div>
            </div>
            <div class="mdl-grid mdl-cell--12-col">
                <div class="mdl-cell mdl-cell--6-col">Altersklassen:</div>
                <div class="mdl-cell mdl-cell--4-col">
                    <ul>
                        {% for ageclass in fencer.get_ageclasses %}
                            <li>
                                {{ ageclass.name }}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="mdl-cell mdl-cell--12-col mdl-grid mdl-shadow--2dp">
            <div class="mdl-cell mdl-cell--6-col">Fechtpass NR:</div>
            <div class="mdl-cell mdl-cell--4-col">{{ fencer.fechtpass|default:"---" }}</div>
        </div>
    </div>

{% endblock %}

OFTM2/apps/fencers_management/templates/fencer_form.html
{% extends "base.html" %}

{% block content %}
    <div class="mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
        <form method="post" class="mdl-cell mdl-cell--12-col mdl-grid" novalidate>
            {% csrf_token %}

            {{ form.non_field_errors }}

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.first_name.id_for_label }}">Vorname</label>
                {{ form.first_name }}
                {{ form.first_name.errors }}
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.last_name.id_for_label }}">Nachname</label>
                {{ form.last_name }}
                {{ form.last_name.errors }}
            </div>


            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select mdl-cell mdl-cell--12-col">
                <input type="text" value="" class="mdl-textfield__input" id="{{ form.gender.id_for_label }}" readonly>
                <input type="hidden" value="" name="gender">
                <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                <label for="{{ form.gender.id_for_label }}" class="mdl-textfield__label">Geschlect</label>
                <ul for="{{ form.gender.id_for_label }}" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    {% for choice in form.fields.gender.choices %}
                        {% if fencer and fencer.gender == choice.0 %}
                        <li class="mdl-menu__item" data-val="{{ choice.0 }}" data-selected="true">{{ choice.1 }}</li>
                        {% else %}
                        <li class="mdl-menu__item" data-val="{{ choice.0 }}">{{ choice.1 }}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
                {{ form.gender.errors }}
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.fechtpass.id_for_label }}">Fechtpass NR.</label>
                {{ form.fechtpass }}
                {{ form.fechtpass.errors }}
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.birthday.id_for_label }}">Geburtsdatum</label>
                {{ form.birthday }}
                {{ form.birthday.errors }}
            </div>
            <div class="mdl-cell--12-col mdl-cell mdl-grid mdl-grid--no-spacing">
                <div class="mdl-layout-spacer"></div>
                <div class="mdl-cell mdl-cell--2-col">
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--red" type="reset">
                        Löschen
                    </button>
                </div>
                <div class="mdl-cell mdl-cell--2-col">
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">
                        Absenden
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

OFTM2/apps/fencers_management/templates/fencers_list.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% block content %}
    <div class="mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
        <div class="mdl-cell mdl-cell--12-col mdl-grid--no-spacing mdl-grid">
            {% if perms.Fencers.can_create %}
                <div class="mdl-layout-spacer"></div>
                <div class="mdl-cell mdl-cell--1-col">
                    <a href="{% url 'fencers_management:fencer_create' %}">
                        <button class="mdl-button mdl-js-button mdl-button--mini-fab">
                            <i class="material-icons">add</i>
                        </button>
                    </a>
                </div>
            {% endif %}</div>
        <div class="mdl-cell mdl-cell--12-col mdl-grid">
            {% render_table table %}
        </div>
    </div>
{% endblock %}