OFTM2/apps/tournament_management/urls.py
'''Tournament Management URL Config'''
from django.urls import path

from . import views

app_name = 'tournament_management'

urlpatterns = [
    path('', views.TournamentsListView.as_view(), name='tournaments_list'),
    path('<int:tournament_id>', views.TournamentsDetailView.as_view(), name='tournament_detail'),
    path('add', views.TournamentCreateView.as_view(), name='tournament_create'),
    path('<int:pk>/update', views.TournamentUpdateView.as_view(), name='tournament_update'),
    path('<int:pk>/delete', views.TournamentDeleteView.as_view(), name='tournament_delete'),
    path('combat/<int:pk>/update', views.CombatUpdateView.as_view(), name='combat_update'),
]

OFTM2/urls.py
"""Root URL Config"""
import debug_toolbar
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='portal.html'), name="portal"),
    path('admin/', admin.site.urls),
    path('fencers/', include('OFTM2.apps.fencers_management.urls')),
                  path('tournaments/', include('OFTM2.apps.tournament_management.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('beamer', include('OFTM2.apps.beamerManagement.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

OFTM2/apps/tournament_management/models.py
from django.core.exceptions import FieldError
from django.db import models
from django.urls import reverse

from OFTM2.apps.fencers_management.models import Fencer, AgeClass


class Tournament(models.Model):
    """Represents a tournament"""
    name = models.CharField(
        verbose_name='Name',
        max_length=60
    )
    date = models.DateField(
        verbose_name="Austragungsdatum",
        blank=True
    )
    participants = models.ManyToManyField(
        Fencer,
        verbose_name="Teilnehmer",
        blank=True
    )
    ageclass = models.ForeignKey(
        AgeClass,
        on_delete=models.CASCADE,
        verbose_name="Altersklasse"
    )

    def __str__(self):
        """Returns the name of the tournament"""
        return self.name

    def participants_count(self):
        """Returns the count of participants"""
        return self.participants.count()

    def get_absolute_url(self):
        """returns the absolute url to the object"""
        return reverse('tournament_management:tournament_detail', args=[str(self.id)])

    def new_round(self):
        """generates a new round with combats"""
        rounds = self.round_set.order_by('round_number').all()
        round_now = rounds.last()
        if round_now:
            r = round_now.round_number + 1
        else:
            r = 1
        round_new = Round(round_number=r, tournament=self, locked=True)
        round_new.save()
        round_new.create_combats()
        return round_new

    participants_count.short_description = "Teilnehmeranzahl"

    class Meta:
        verbose_name = "Tunier"
        verbose_name_plural = "Turniere"


class Round(models.Model):
    """Represents a round"""
    round_number = models.IntegerField(
        verbose_name="Runde"
    )

    tournament = models.ForeignKey(
        Tournament,
        on_delete=models.CASCADE,
        verbose_name="Tunier"
    )

    locked = models.BooleanField(
        verbose_name="Gesperrt",
        default=False
    )

    def __str__(self):
        """Returns a assembeld name"""
        return "Runde " + self.round_number.__str__() + " vom Tunier " + self.tournament.__str__()

    def save(self, *args, **kwargs):
        try:
            original = Round.objects.get(pk=self.pk)
            if original.locked:
                raise FieldError('"{}" is locked.'.format(self.__str__()))
            super(Round, self).save(*args, **kwargs)
        except self.DoesNotExist:
            super(Round, self).save(*args, **kwargs)

    def get_round_before(self):
        if self.round_number <= 1:
            return None
        else:
            return self.tournament.round_set.get(round_number__exact=self.round_number - 1)

    def create_combats(self):
        if not self.started():
            result = []
            if self.round_number == 1:
                p = list(self.tournament.participants.order_by('?'))
            else:
                p = []
                for point in Round.objects.get(tournament=self.tournament, round_number=self.round_number-1).ranking():
                    p.append(point.fencer)

            while p:
                c = Combat(related_round_id=self.pk, fighter1=p.pop(0), fighter2=p.pop(0))
                c.save()
                result.append(c)
            return result
        else:
            raise Exception('round has already started')

    def finish(self):
        for c in self.combat_set.all():
            c.finish()

    def started(self):
        if self.combat_set.count() == 0:
            return False
        else:
            return True

    def finished(self):
        finished = True
        for c in self.combat_set.all():
            if not c.locked and c.result_set.count() == 0:
                finished = False
        return finished

    def complete(self):
        complete = True
        for c in self.combat_set.all():
            if not c.fighter2_points and not c.fighter1_points:
                complete = False
        return complete

    def ranking(self):
        return self.points_set.order_by('-wins', '-given', '-index', 'fencer_id')

    class Meta:
        verbose_name = "Runde"
        verbose_name_plural = "Runden"


class Combat(models.Model):
    """Represents a combat"""
    related_round = models.ForeignKey(
        Round,
        on_delete=models.CASCADE,
        verbose_name="Runde"
    )

    fighter1 = models.ForeignKey(
        Fencer,
        on_delete=models.CASCADE,
        verbose_name="Kämpfer 1",
        related_name="+"
    )

    fighter2 = models.ForeignKey(
        Fencer,
        on_delete=models.CASCADE,
        verbose_name="Kämpfer 2",
        related_name="+"
    )

    fighter1_points = models.IntegerField(
        verbose_name="Punkte Fechter 1",
        blank=True,
        null=True
    )

    fighter2_points = models.IntegerField(
        verbose_name="Punkte Fechter 2",
        blank=True,
        null=True
    )

    locked = models.BooleanField(
        verbose_name="Gesperrt",
        default=False
    )

    def __str__(self):
        """Returns a assembeld name"""
        return "Kampf: " + self.fighter1.__str__() + " vs " + self.fighter2.__str__() + " (" + self.related_round.__str__() + ")"

    def get_winner(self):
        """Returns the winner"""
        if self.fighter1_points > self.fighter2_points:
            return self.fighter1
        elif self.fighter1_points == self.fighter2_points:
            return None
        else:
            return self.fighter2

    def get_update_url(self):
        """returns the update url to the object"""
        return reverse('tournament_management:combat_update', args=[str(self.id)])

    def finish(self):
        if not self.locked and self.result_set.count() == 0:
            self.locked = True
            self.save()
        elif self.result_set.count() > 0:
            raise Exception('{} ist schon ausgewertet'.format(self.__str__()))
        if self.related_round.round_number > 1:
            previous_round = self.related_round.tournament.round_set.get(round_number=self.related_round.round_number-1)
            last_points = previous_round.points_set.get(fencer=self.fighter1, related_round=previous_round)
        p, created = Points.objects.get_or_create(fencer=self.fighter1, related_round=self.related_round)
        if self.related_round.round_number > 1:
            p.recieved += self.fighter2_points + last_points.recieved
            p.given += self.fighter1_points + last_points.given
            p.wins = last_points.wins
        else:
            p.recieved += self.fighter2_points
            p.given += self.fighter1_points
        if self.get_winner() == self.fighter1:
            p.wins += 1
        p.save()

        if self.related_round.round_number > 1:
            last_points = previous_round.points_set.get(fencer=self.fighter2, related_round=previous_round)
        p, created = Points.objects.get_or_create(fencer=self.fighter2, related_round=self.related_round)
        if self.related_round.round_number > 1:
            p.recieved += self.fighter1_points + last_points.recieved
            p.given += self.fighter2_points + last_points.given
            p.wins = last_points.wins
        else:
            p.recieved += self.fighter1_points
            p.given += self.fighter2_points
        if self.get_winner() == self.fighter2:
            p.wins += 1
        p.save()

    def save(self, *args, **kwargs):
        try:
            original = Combat.objects.get(pk=self.pk)
            if original.locked:
                raise FieldError('"{}" is locked.'.format(self.__str__()))
            super(Combat, self).save(*args, **kwargs)
        except self.DoesNotExist:
            super(Combat, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Kampf"
        verbose_name_plural = "Kämpfe"


class Result(models.Model):
    related_round = models.ForeignKey(
        Round,
        on_delete=models.CASCADE,
        verbose_name="Runde"
    )
    combat = models.ForeignKey(
        Combat,
        on_delete=models.PROTECT,
        verbose_name="Kampf"
    )
    winner = models.ForeignKey(
        Fencer,
        on_delete=models.PROTECT,
        verbose_name="Sieger",
        related_name="+"
    )
    looser = models.ForeignKey(
        Fencer,
        on_delete=models.PROTECT,
        verbose_name="Verlierer",
        related_name="+"
    )
    winner_given = models.IntegerField(
        verbose_name="Sieger gegeben"
    )
    winner_received = models.IntegerField(
        verbose_name="Sieger erhalten"
    )
    looser_given = models.IntegerField(
        verbose_name="Verlierer gegben"
    )
    looser_received = models.IntegerField(
        verbose_name="Verlierer erhalten"
    )

    class Meta:
        verbose_name = "Ergebniss"
        verbose_name_plural = "Ergebnisse"


class Points(models.Model):
    related_round = models.ForeignKey(
        Round,
        on_delete=models.CASCADE,
        verbose_name="Runde"
    )
    fencer = models.ForeignKey(
        Fencer,
        on_delete=models.CASCADE,
        verbose_name="Fechter"
    )
    recieved = models.IntegerField(
        verbose_name="Erhaltene Treffer",
        default=0
    )
    given = models.IntegerField(
        verbose_name="Gegebene Treffer",
        default=0
    )

    index = models.IntegerField(
        verbose_name="Index",
        default=0
    )

    wins = models.IntegerField(
        verbose_name="Siege",
        default=0
    )

    def save(self, *args, **kwargs):
        self.index = self.given - self.recieved
        super(Points, self).save(*args, **kwargs)

    def __str__(self):
        return "Punkte für {}".format(self.fencer)

    class Meta:
        verbose_name = "Punkte"
        verbose_name_plural = "Punkte"

OFTM2/apps/tournament_management/forms.py
"""Forms for fencers_management"""

from django.forms import ModelForm

from OFTM2.apps.tournament_management.models import Tournament, Combat


class TournamentForm(ModelForm):
    class Meta:
        model = Tournament
        fields = ['name', 'date', 'ageclass', 'participants']

    def __init__(self, *args, **kwargs):
        super(TournamentForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'mdl-textfield__input'


class CombatForm(ModelForm):
    class Meta:
        model = Combat
        fields = ['fighter1', 'fighter1_points', 'fighter2', 'fighter2_points']

    def __init__(self, *args, **kwargs):
        super(CombatForm, self).__init__(*args, **kwargs)
        self.fields['fighter1'].disabled = True
        self.fields['fighter2'].disabled = True
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'mdl-textfield__input'

OFTM2/apps/tournament_management/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_tables2 import RequestConfig
from django.http import HttpResponseRedirect

from OFTM2.apps.fencers_management.helpers import calculate_birthday
from OFTM2.apps.fencers_management.models import Fencer
from OFTM2.apps.fencers_management.tables import FencersTable
from OFTM2.apps.tournament_management.forms import TournamentForm, CombatForm
from OFTM2.apps.tournament_management.models import Tournament, Combat, Points
from OFTM2.apps.tournament_management.tables import TournamentTable, CombatTable, PointsTable


class TournamentsListView(PermissionRequiredMixin, View):
    permission_required = 'Tournament.can_view'
    """show all tournaments as a table"""

    def get(self, request):
        """HTTP-GET"""
        table = TournamentTable(Tournament.objects.all())
        RequestConfig(request).configure(table)
        return render(request, 'tournaments_list.html', {'table': table, 'title': "Liste der Tuniere"})


class TournamentsDetailView(PermissionRequiredMixin, View):
    permission_required = 'Tournament.can_view'
    """show one tournament"""

    def get(self, request, tournament_id):
        """HTTP-GET"""
        tournament = get_object_or_404(Tournament, pk=tournament_id)
        participants_table = FencersTable(tournament.participants.all())
        if tournament.round_set.count() > 1:
            points_table = PointsTable(tournament.round_set.get(round_number=tournament.round_set.last().round_number-1, tournament=tournament).ranking())
        else:
            points_table = None
        rounds = []
        if request.GET.get('action'):
            if request.GET.get('action') == 'start':
                tournament.new_round()
                return HttpResponseRedirect(reverse_lazy('tournament_management:tournament_detail', kwargs={'tournament_id': tournament.pk}))
            elif request.GET.get('action') == 'newRound':
                tournament.round_set.last().finish()
                tournament.new_round()
                return HttpResponseRedirect(reverse_lazy('tournament_management:tournament_detail', kwargs={'tournament_id': tournament.pk}))
        for r in tournament.round_set.all():
            r.combat_table = CombatTable(r.combat_set.all())
            rounds.append(r)
        return render(request, 'tournament_detail.html',
                      {'tournament': tournament, 'participants_table': participants_table, 'back': True, 'title': tournament, 'rounds': rounds, 'points_table': points_table})


class TournamentCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'Tournament.can_create'
    """create a new tournament"""
    form_class = TournamentForm
    template_name = 'tournament_form.html'
    model = Tournament


class TournamentUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'Tournament.can_edit'
    """update a tournament"""
    form_class = TournamentForm
    template_name = 'tournament_form.html'
    model = Tournament

    def dispatch(self, request, *args, **kwargs):
        t = Tournament.objects.get(pk=kwargs['pk'])
        ac = t.ageclass
        self.form_class.base_fields['participants'].queryset = Fencer.objects.filter(
            birthday__range=[calculate_birthday(t.date, ac.endAge), calculate_birthday(t.date, ac.startAge)])
        return super(TournamentUpdateView, self).dispatch(request, *args, **kwargs)


class TournamentDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'Tournament.can_delete'
    """delete a tournament"""
    form_class = TournamentForm
    template_name = 'tournament_delete.html'
    model = Tournament
    success_url = reverse_lazy('tournament_management:tournaments_list')


class CombatUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'Combat.can_modify'
    """update a combat"""
    form_class = CombatForm
    template_name = 'combat_form.html'
    model = Combat

    def get_success_url(self):
        return "{}#round{}".format(reverse_lazy('tournament_management:tournament_detail', kwargs={'tournament_id': self.object.related_round.tournament.id}), self.object.related_round.round_number)

OFTM2/apps/tournament_management/templates/combat_form.html
{% extends "base.html" %}

{% block content %}
    <div class="mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
        <form method="post" class="mdl-cell mdl-cell--12-col mdl-grid" novalidate>
            {% csrf_token %}

            {{ form.non_field_errors }}

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.fighter1.id_for_label }}">Kämpfer 1</label>
                {{ form.fighter1 }}
                {{ form.fighter1.errors }}
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.fighter1_points.id_for_label }}">Punkte Kämpfer 1</label>
                {{ form.fighter1_points }}
                {{ form.fighter1_points.errors }}
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.fighter2.id_for_label }}">Kämpfer 2</label>
                {{ form.fighter2 }}
                {{ form.fighter2.errors }}
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.fighter2_points.id_for_label }}">Punkte Kämpfer 2</label>
                {{ form.fighter2_points }}
                {{ form.fighter2_points.errors }}
            </div>


            <div class="mdl-cell--12-col mdl-cell mdl-grid mdl-grid--no-spacing">
                <div class="mdl-layout-spacer"></div>
                <div class="mdl-cell mdl-cell--2-col">
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--red" type="reset">
                        Löschen
                    </button>
                </div>
                <div class="mdl-cell mdl-cell--2-col">
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">
                        Absenden
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

OFTM2/apps/tournament_management/templates/tournament_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="mdl-cell mdl-cell--12-col mdl-grid mdl-shadow--2dp mdl-color--white">
        <div class="mdl-layout-spacer"></div>
        <div class="mdl-cell--4-col">
            <form method="post">
                {% csrf_token %}
                <p style="text-align: center">
                    Tunier {{ tournament.name }} wirklich löschen?<br>
                    <a href="{{ tournament.get_absolute_url }}">
                        <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="button">
                            Abbruch
                        </button>
                    </a>
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--red" type="submit">
                        Bestätigen
                    </button>
                </p>
            </form>
        </div>
        <div class="mdl-layout-spacer"></div>
    </div>
{% endblock %}

OFTM2/apps/tournament_management/templates/tournament_detail.html
{% extends "base.html" %}

{% block content %}
    {% if perms.Fencers.can_modify or perms.Fencers.can_delete %}
        <div class="mdl-color--white mdl-shadow--2dp mdl-cell--12-col mdl-cell mdl-grid">
            <div class="mdl-layout-spacer"></div>
            {% if perms.Tournament.can_delete %}
                <div class="mdl-cell--1-col mdl-cell">
                    <a href="{% url 'tournament_management:tournament_delete' tournament.pk %}">
                        <button class="mdl-button mdl-js-button mdl-button--mini-fab mdl-button--colored mdl-color--red mdl-color-text--white">
                            <i class="material-icons">delete</i>
                        </button>
                    </a>
                </div>
            {% endif %}
            {% if perms.Tournament.can_modify and not tournament.round_set.all %}
                <div class="mdl-cell--1-col mdl-cell">
                    <a href="{% url 'tournament_management:tournament_update' tournament.pk %}">
                        <button class="mdl-button mdl-js-button mdl-button--mini-fab mdl-button--colored mdl-shadow--2dp">
                            <i class="material-icons">edit</i>
                        </button>
                    </a>
                </div>
            {% endif %}
        </div>
    {% endif %}
    <div class="mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
        <div class="mdl-cell mdl-cell--4-col mdl-grid mdl-shadow--2dp">
            <div class="mdl-cell mdl-cell--6-col">Name:</div>
            <div class="mdl-cell mdl-cell--4-col">{{ tournament.name }}</div>
        </div>
        <div class="mdl-cell mdl-cell--4-col mdl-grid mdl-shadow--2dp">
            <div class="mdl-cell mdl-cell--6-col">Austragungsdatum:</div>
            <div class="mdl-cell mdl-cell--4-col">{{ tournament.date }}</div>
        </div>
        <div class="mdl-cell mdl-cell--4-col mdl-grid mdl-shadow--2dp">
            <div class="mdl-cell mdl-cell--6-col">Altersklasse:</div>
            <div class="mdl-cell mdl-cell--4-col">{{ tournament.ageclass }}</div>
        </div>
    </div>
    <div class="mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
        {% if not points_table %}
        <h5>Teilnehmer</h5>
        {% load django_tables2 %}
        {% render_table participants_table %}
        {% else %}
        <h5>Ergebnisse</h5>
        {% load django_tables2 %}
        {% render_table points_table %}
        {% endif %}
    </div>
    <div class="mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
        <h5 id="fights">Kämpfe</h5>
        {% if rounds %}
            <div class="mdl-cell mdl-cell--12-col">
                {% load django_tables2 %}
                {% for round in rounds %}
                    <h6 id="round{{ round.round_number }}">
                        Runde {{ round.round_number }}
                        {% if not round.finished and round.complete %}
                        <a href="{% url 'tournament_management:tournament_detail' tournament.id %}?action=newRound">
                            <button class="mdl-button mdl-js-button mdl-button--mini-fab mdl-button--colored mdl-shadow--2dp">
                                <i class="material-icons">send</i> Nächste Runde
                            </button>
                        </a>
                        {% endif %}
                    </h6>
                    {% render_table round.combat_table %}
                {% endfor %}
            </div>
        {% else %}
            <div class="mdl-cell mdl-cell--12-col">
            <h6>Das Tunier hat noch nicht begonnen!</h6>
            {% if tournament.participants_count > 1 and tournament.participants_count|divisibleby:2 %}
                <a href="{% url 'tournament_management:tournament_detail' tournament.pk %}?action=start">
                    <button class="mdl-button mdl-js-button mdl-button--mini-fab mdl-button--colored mdl-shadow--2dp">
                        <i class="material-icons">send</i> Tunier starten
                    </button>
                </a>
            {% else %}
                <h6>Starten nicht möglich zu wenige Teilnehmner oder ungerade Teilnehmnerzahl!</h6>
            {% endif %}
            <div></div>
        {% endif %}
        </div>
{% endblock %}

OFTM2/apps/tournament_management/templates/tournament_form.html
{% extends "base.html" %}

{% block content %}
    <div class="mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
        <form method="post" class="mdl-cell mdl-cell--12-col mdl-grid" novalidate>
            {% csrf_token %}

            {{ form.non_field_errors }}

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.name.id_for_label }}">Name</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label class="mdl-textfield__label mdl-color-text--grey" for="{{ form.date.id_for_label }}">Austragungsdatum</label>
                {{ form.date }}
                {{ form.date.errors }}
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select mdl-cell mdl-cell--12-col">
                <input type="text" value="" class="mdl-textfield__input" id="{{ form.ageclass.id_for_label }}" readonly>
                <input type="hidden" value="" name="ageclass">
                <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                <label for="{{ form.ageclass.id_for_label }}" class="mdl-textfield__label">Altersklasse</label>
                <ul for="{{ form.ageclass.id_for_label }}" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    {% for choice in form.fields.ageclass.choices %}
                        {% if tournament and tournament.ageclass.pk == choice.0 %}
                            <li class="mdl-menu__item" data-val="{{ choice.0 }}" data-selected="true">{{ choice.1 }}</li>
                        {% else %}
                            <li class="mdl-menu__item" data-val="{{ choice.0 }}">{{ choice.1 }}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
                {{ form.gender.errors }}
            </div>

            {{ form.participants }}

            <div class="mdl-cell--12-col mdl-cell mdl-grid mdl-grid--no-spacing">
                <div class="mdl-layout-spacer"></div>
                <div class="mdl-cell mdl-cell--2-col">
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-color--red" type="reset">
                        Löschen
                    </button>
                </div>
                <div class="mdl-cell mdl-cell--2-col">
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">
                        Absenden
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

OFTM2/apps/tournament_management/templates/tournaments_list.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% block content %}
    <div class="mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
        <div class="mdl-cell mdl-cell--12-col mdl-grid--no-spacing mdl-grid">
            {% if perms.Fencers.can_create %}
                <div class="mdl-layout-spacer"></div>
                <div class="mdl-cell mdl-cell--1-col">
                    <a href="{% url 'tournament_management:tournament_create' %}">
                        <button class="mdl-button mdl-js-button mdl-button--mini-fab">
                            <i class="material-icons">add</i>
                        </button>
                    </a>
                </div>
            {% endif %}</div>
        <div class="mdl-cell mdl-cell--12-col mdl-grid">
            {% render_table table %}
        </div>
    </div>
{% endblock %}